# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run script
        run: mvn compile
        working-directory: .m2/repository
        
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run test
        run: mvn test
        working-directory: .m2/repository

  package:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run package
        run: mvn package
        working-directory: .m2/repository
        
  deploy_test:
    runs-on: self-hosted
    needs: package
    env:
      name: test
      action: start
      url: http://localhost:8080/game2048
      on_stop: stop_test
    steps:
      - name: Remove docker
        run: docker rm --force game2048
      - name: Remove dockerimage
        run: docker image rm --force game2048
      - name: Echo text
        run: echo -e 'FROM tomcat:9.0.46-jdk11 \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
      - name: Run docker
        run: docker run --rm -d --name game2048 -p 8080:8080 game2048
     
  stop_test:
    runs-on: self-hosted
    env:
       name: test
       action: stop
    steps:
        - name: Remove docker
          run: docker rm --force game2048
        - name: Remove dockerimage
          run: docker image rm --force game2048
