
name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
env:
  maven_packages_cache: ".m2/repository"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Maven Packages Cache
        uses: actions/cache@v2
        with:
          path: $maven_packages_cache
          key: ${{ runner.os }}-build
      - name: Checkout
        uses: actions/checkout@v2  
      - name: Build Webapplication
        run: mvn compile
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: "target/*"  
        
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Maven Packages Cache
        uses: actions/cache@v2
        with:
          path: $maven_packages_cache
          key: ${{ runner.os }}-build
      - name: Run test
        run: mvn test

  package:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Maven Packages Cache
        uses: actions/cache@v2
        with:
          path: $maven_packages_cache
          key: ${{ runner.os }}-build
      - name: Create war package
        run: mvn package -Dmaven.test.skip=true
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: war
          path: "target/*.war"  
        
  deploy_test:
    runs-on: self-hosted
    needs: package
    env:
      name: test
      url: http://localhost:8081/game2048
    steps:
      - name: Start game2048
        run: cp -f ./target/game2048.war /usr/local/tomcat/webapps
     

